version: "3.8"

services:
    botobot_api:
        image: botobot_api
        container_name: botobot_api
        ports:
            - "5000:5000"
        hostname: botobot_api
        restart: always
        networks:
            - botobot-net

    botobot_telegram:
        image: botobot_telegram
        container_name: botobot_telegram
        hostname: botobot_telegram
        restart: always
        networks:
            - botobot-net

    botobot_whatsapp:
        image: botobot_whatsapp
        container_name: botobot_whatsapp
        ports:
            - "8500:8500"
        hostname: botobot_whatsapp
        restart: always
        networks:
            - botobot-net

networks:
  botobot-net:
    driver: bridge
