[default]
DEBUG = false
TITLE = "Botobot Chatbot"
SECRET_KEY = "somerandomkey"
SQLALCHEMY_DATABASE_URI = 'sqlite:///botobot.db'
SQLALCHEMY_TRACK_MODIFICATIONS  = 0

EXTENSIONS = [
    "botobot_core.ext.database:init_app",
    "botobot_core.ext.commands:init_app"
]

RESTAPI_RESOURCES = [
    "botobot_core.blueprints.restapi.menu.MenuResource:/",
    "botobot_core.blueprints.restapi.statictext.StaticTextResource:/statictext/<topic>",
    "botobot_core.blueprints.restapi.stocks.StocksResource:/stocks",
    "botobot_core.blueprints.restapi.weather.WeatherResource:/weather"
]

[development]
DEBUG = true
